<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

$sections = $block->getSections();

if (!count($sections)) {
    return null;
}

$uniqueId = '_' . uniqid('');

// Content type configurations
$title = $block->getBlockTitle();
$subTitle = $block->getBlockSubTitle();
$isShowAllButtonEnabled = $block->getIsShowAllEnabled();
$mobileGridCols = $block->getGridColumnsMobile();
$tabletGridCols = $block->getGridColumnsTablet();
$desktopGridCols = $block->getGridColumnsDesktop();

?>

<div>
    <?php if ($title): ?>
        <h2 class="content-block-title">
            <?= $escaper->escapeHtml($title) ?>
        </h2>
    <?php endif; ?>
    <?php if ($subTitle): ?>
        <p class="content-block-subtitle">
            <?= $escaper->escapeHtml($subTitle) ?>
        </p>
    <?php endif; ?>
    <div class="grid grid-cols-<?= $mobileGridCols ?> md:grid-cols-<?= $tabletGridCols ?> lg:grid-cols-<?= $desktopGridCols ?> gap-4">
        <?php foreach ($sections as $index => $section): ?>
            <?= $this->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Scandiweb_ContentTypes::content-type/featured-categories/card/default.phtml')
                ->setData('section', $section)
                ->toHtml(); ?>
        <?php endforeach; ?>
    </div>
</div>