<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

$sections = $block->getSections();

if (!count($sections)) {
    return;
}

// Content type configurations
$blockTitle = $block->getBlockTitle();
$blockSubTitle = $block->getBlockSubTitle();
$ctaType = $block->getCtaType();
$uspCardColor = $block->getUspColor();
$mobileGridCols = $block->getGridColumnsMobile();
$tabletGridCols = $block->getGridColumnsTablet();
$desktopGridCols = $block->getGridColumnsDesktop();
?>

<div class="p-3 md:px-6">
    <?php if ($blockTitle): ?>
        <h2 class="content-block-title">
            <?= $escaper->escapeHtml($blockTitle) ?>
        </h2>
    <?php endif; ?>
    <?php if ($blockSubTitle): ?>
        <p class="content-block-subtitle">
            <?= $escaper->escapeHtml($blockSubTitle) ?>
        </p>
    <?php endif; ?>
    <div class="grid grid-cols-<?= $mobileGridCols ?> md:grid-cols-<?= $tabletGridCols ?> lg:grid-cols-<?= $desktopGridCols ?> gap-4">
        <?php foreach ($sections as $index => $section): ?>
            <?= $this->getLayout()
                ->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Scandiweb_ContentTypes::content-type/usp/card/minimalistic.phtml')
                ->setData('section', $section)
                ->setData('usp_card_color', $uspCardColor)
                ->setData('cta_type', $ctaType)
                ->toHtml(); ?>
        <?php endforeach; ?>
    </div>
</div>