<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

?>
<script>
    'use strict';

    (() => {
        const initCarousels = (elements) => {
            const initSlider = (slider) => {
                slider.innerHTML = `<div data-role="swiper-wrapper" class="swiper-wrapper">${slider.innerHTML}</div>`;
                slider.parentElement.classList.add('relative');
                slider.insertAdjacentHTML(
                    'beforeend',
                    '<?= $escaper->escapeJs($this->getLayout()
                                ->createBlock('Magento\Framework\View\Element\Template')
                                ->setTemplate('Scandiweb_ContentTypes::carousel-nav.phtml')
                                ->setData('is_show_arrows', true)
                                ->setData('pagination', 'dots')
                                ->setData('arrows_container_class', 'max-lg:mb-6')
                                ->setData('pagination_container_class', 'my-6')
                                ->toHtml())
                ?>');
                slider.classList.add('swiper');
                slider.classList.add('swiper-slider-content');

                const slides = slider.querySelectorAll('[data-content-type="slide"]');

                slides.forEach(slide => {
                    slide.classList.add('swiper-slide');
                });

                const isAutoplay = slider.dataset.autoplay === 'true';
                const autoplaySpeed = slider.dataset.autoplaySpeed;
                const isLoop = slider.dataset.infiniteLoop === 'true';

                const swiperOptions = {
                    spaceBetween: 0,
                    loop: isLoop,
                    speed: 800,
                    threshold: 20,
                    autoHeight: true,
                    navigation: {
                        nextEl: '.swiper-button-next',
                        prevEl: '.swiper-button-prev',
                    },
                    pagination: {
                        el: '.swiper-pagination',
                        type: 'bullets',
                        dynamicBullets: true,
                        dynamicMainBullets: 4,
                        clickable: true,
                    },
                    mousewheel: {
                        forceToAxis: true,
                        thresholdDelta: 10,
                    },
                    autoplay: isAutoplay && autoplaySpeed ? {
                        delay: autoplaySpeed
                    } : undefined,
                };

                initSwiperSlider(slider, swiperOptions);
            }

            elements.forEach(element => {
                if (element.dataset.contentType === 'slider') {
                    initSlider(element);
                }
            });
        };


        document.addEventListener('alpine:init', () => {
            const carouselElements = document.querySelectorAll(
                `[data-content-type="products"][data-appearance="carousel"],
                [data-content-type="slider"],[data-content-type="products"][data-appearance="insider_carousel"]`
            );

            if (carouselElements.length > 0) {
                initCarousels(carouselElements);
            }
        });
    })();
</script>
<?php $hyvaCsp->registerInlineScript() ?>
