<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Scandiweb\StyleGuide\ViewModel\SectionBlocksProvider $viewModel */
$viewModel = $block->getData('view_model');
$sectionBlocks = $viewModel->getSectionBlocks();
?>
<div class="style-guide-container">
    <dl class="flex flex-col gap-10">
        <?php foreach ($sectionBlocks as $block): ?>
            <?php $html = trim($block->toHtml()); ?>
            <?php if ($html): ?>
                <div>
                    <div class="pt-2 pb-3 mb-8 text-2xl border-b border-grey-600 px-4">
                        <?= $escaper->escapeHtml($block->getTitle()); ?>
                    </div>
                    <?= $block->toHtml() ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </dl>
</div>