<?php
$section = $block->getData('section');
$ctaType = $block->getData('cta_type');

$title = $section['title'];
$description = $section['description'];
$image = $section['image'];
$ctaText = $section['cta_text'];
$url = $section['url'];
$openInNewTab = $section['open_new_tab'];
?>
<div
    class="bg-white flex-col gap-5 rounded-xs relative">
    <img
        class="w-full rounded-xs aspect-[4/6]"
        src="<?= $escaper->escapeHtmlAttr($image) ?>"
        alt="<?= $escaper->escapeHtmlAttr($title)  ?>"
        width="400"
        height="600"
        loading="lazy">
    <div class="flex flex-col gap-8 p-4 lg:p-6 absolute top-0">
        <div class="flex flex-col gap-3">
            <h3><?= $escaper->escapeHtml($title) ?></h3>
            <div><?= html_entity_decode($description) ?></div>
        </div>
        <?php if ($ctaText): ?>
            <a
                href="<?= $escaper->escapeUrl($url) ?>"
                <?php if ($openInNewTab): ?>
                    target="_blank"
                <?php endif; ?>
                class="w-full lg:w-max <?= $escaper->escapeHtmlAttr($ctaType) ?>"
                title="<?= $escaper->escapeHtmlAttr($title) ?>">
                <?= $escaper->escapeHtml($ctaText) ?>
            </a>
        <?php endif; ?>
    </div>
</div>