<?php
$section = $block->getData('section');
$promoCardColor = $block->getData('promo_card_color');
$ctaType = $block->getData('cta_type');

$title = $section['title'];
$description = $section['description'];
$image = $section['image'];
$ctaText = $section['cta_text'];
$url = $section['url'];
$openInNewTab = $section['open_new_tab'];
?>
<div
    class="bg-white flex max-lg:flex-col-reverse rounded-xs"
    <?php if ($promoCardColor): ?>
    style="background-color: <?= $promoCardColor ?>;"
    <?php endif; ?>>
    <div class="flex flex-col gap-8 p-4 lg:p-6 lg:w-full max-lg:h-full">
        <div class="flex flex-col gap-3">
            <h4><?= $escaper->escapeHtml($title) ?></h4>
            <div><?= html_entity_decode($description) ?></div>
        </div>
        <?php if ($ctaText): ?>
            <a
                href="<?= $escaper->escapeUrl($url) ?>"
                <?php if ($openInNewTab): ?>
                    target="_blank"
                <?php endif; ?>
                class="w-full lg:w-max mt-auto <?= $escaper->escapeHtmlAttr($ctaType) ?>"
                title="<?= $escaper->escapeHtmlAttr($title) ?>">
                <?= $escaper->escapeHtml($ctaText) ?>
            </a>
        <?php endif; ?>
    </div>
    <img
        class="w-full rounded-xs aspect-square lg:max-w-60"
        src="<?= $escaper->escapeHtmlAttr($image) ?>"
        alt="<?= $escaper->escapeHtmlAttr($title)  ?>"
        width="240"
        height="240"
        loading="lazy">
</div>