<?php
/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>

<button
    class="font-bold text-primary underline mt-1"
    @click="handleOpenReadMore"
    :class="{ 'max-md:hidden': !isTruncateMobile, 'md:hidden': !isTruncateDesktop }"
    x-text="isOpened ? '<?= __('Read less') ?>' : '<?= __('Read more') ?>'"
>
</button>