<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var HeroiconsOutline $heroicons */

$heroicons = $viewModels->require(HeroiconsOutline::class);

?>
<div class="flex flex-col gap-10">
    <div class="flex flex-wrap gap-10 lg:gap-20 font-bold">
        <div class="flex flex-col gap-6 max-md:hidden">
            <div class="h-6"></div>
            <span class="h-12 flex items-center">Default</span>
            <span class="h-12 flex items-center">Disabled</span>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Primary Buttons</div>
            <button class="w-full btn btn-primary">Button text</button>
           <button class="w-full btn btn-primary" disabled>Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Primary Button with left Icon</div>
            <button class="w-full btn btn-primary"><?= $heroicons->shoppingCartHtml() ?> Button text</button>
            <button class="w-full btn btn-primary" disabled><?= $heroicons->shoppingCartHtml() ?> Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Primary Button with right Icon</div>
            <button class="w-full btn btn-primary">Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
            <button class="w-full btn btn-primary" disabled>Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
        </div>
    </div>
    <div class="flex flex-wrap gap-10 lg:gap-20 font-bold">
        <div class="flex flex-col gap-6 max-lg:hidden">
            <div class="h-6"></div>
            <span class="h-12 flex items-center">Default</span>
            <span class="h-12 flex items-center">Disabled</span>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Secondary Buttons</div>
            <button class="w-full btn btn-secondary">Button text</button>
            <button class="w-full btn btn-secondary" disabled>Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div class="w-max">Secondary Buttons with left Icon</div>
            <button class="w-full btn btn-secondary"><?= $heroicons->shoppingCartHtml() ?> Button text</button>
            <button class="w-full btn btn-secondary" disabled><?= $heroicons->shoppingCartHtml() ?> Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div class="w-max">Secondary Buttons with right Icon</div>
            <button class="w-full btn btn-secondary">Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
            <button class="w-full btn btn-secondary" disabled>Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
        </div>
    </div>
    <div class="flex flex-wrap gap-10 lg:gap-20 font-bold">
        <div class="flex flex-col gap-6 max-lg:hidden">
            <div class="h-6"></div>
            <span class="h-12 flex items-center">Default</span>
            <span class="h-12 flex items-center">Disabled</span>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Tritical Buttons</div>
            <button class="btn">Button text</button>
            <button class="btn" disabled>Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Tritical Buttons with left Icon</div>
            <button class="btn"><?= $heroicons->shoppingCartHtml() ?> Button text</button>
            <button class="btn" disabled><?= $heroicons->shoppingCartHtml() ?> Button text</button>
        </div>
        <div class="flex flex-col gap-6 w-60">
            <div>Tritical Buttons with right Icon</div>
            <button class="btn">Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
            <button class="btn" disabled>Button text <?= $heroicons->arrowRightHtml('rtl:rotate-180') ?></button>
        </div>
    </div>
</div>