<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="flex gap-10">
    <div class="flex flex-col gap-5">
        <table class="w-32">
            <caption>Caption text</caption>
        </table>
        <table class="w-32">
            <caption class="font-bold">Caption text</caption>
        </table>
        <table class="w-32">
            <caption><a href="#">Caption text link</a></caption>
        </table>
    </div>
    <div class="flex flex-col gap-5">
        <small>Small caption text
        </small>
        <small class="font-bold">Small caption text
        </small>
        <small><a href="#">Small caption text link</a></small>
    </div>
</div>