<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<h1><?= $escaper->escapeHtml(__('H1 Heading')) ?></h1>
<h2><?= $escaper->escapeHtml(__('H2 Heading')) ?></h2>
<h3><?= $escaper->escapeHtml(__('H3 Heading')) ?></h3>
<h4><?= $escaper->escapeHtml(__('H4 Heading')) ?></h4>
<h5><?= $escaper->escapeHtml(__('H5 Heading')) ?></h5>
<h6><?= $escaper->escapeHtml(__('H6 Heading')) ?></h6>
