<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_StyleGuide
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

declare(strict_types=1);

/** @var \Scandiweb\StyleGuide\Block\Section $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div x-data="{}"class="flex flex-wrap gap-3">
    <button
        class="btn btn-primary bg-green-500 hover:bg-green-500"
        @click="window.dispatchMessages([
            {
                type: 'success',
                text: 'Use color to accentuate the message.'
            }
        ], 10000)">
        <span><?= __('Success') ?></span>
    </button>
    <button
        class="btn btn-primary bg-yellow-300 hover:bg-yellow-300"
        @click="window.dispatchMessages([
            {
                type: 'warning',
                text: 'Use color to accentuate the message.'
            }
        ], 10000)">
        <span><?= __('Warning') ?></span>
    </button>
    <button
        class="btn btn-primary bg-red-500 hover:bg-red-500"
        @click="window.dispatchMessages([
            {
                type: 'error',
                text: 'Use color to accentuate the message.'
            }
        ], 10000)">
        <span><?= __('Error') ?></span>
    </button>
    <button
        class="btn btn-primary bg-blue hover:bg-blue-500"
        @click="window.dispatchMessages([
            {
                type: 'info',
                text: 'Use color to accentuate the message.'
            }
        ], 10000)">
        <span><?= __('Info') ?></span>
    </button>
    <button
        class="btn btn-primary"
        @click="window.dispatchMessages([
            {
                text: 'Use color to accentuate the message.'
            }
        ], 10000)">
        <span><?= __('No type') ?></span>
    </button>
</div>
<p class="pt-6">Click on button and message will appear for 10sec</p>
