<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$sections = $block->getSections();

if (!count($sections)) {
    return null;
}

$uniqueId = '_' . uniqid('');

$numberOfSlides = count($sections);

// Slider configurations
$isSliderInfinitive = $block->getData('slider_infinitive');
$isSliderShowArrows = $block->getData('slider_show_arrows');

$sliderCountMobile = $block->getData('slider_count_mobile') > $numberOfSlides ? $numberOfSlides : $block->getData('slider_count_mobile');
$sliderCountTablet = $block->getData('slider_count_tablet') > $numberOfSlides ? $numberOfSlides : $block->getData('slider_count_tablet');
$sliderCountDesktop = $block->getData('slider_count_desktop') > $numberOfSlides ? $numberOfSlides : $block->getData('slider_count_desktop');

$isPreview = $block->getPreview();
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$notificationBgColor = $storeConfig->getStoreConfig('hyva_theme_content/notification_bar/background_color');
?>

<script>
    function initNotificationCarousel<?= $uniqueId ?>() {
        return {
            init() {
                const swiperOptions = {
                    loop: <?= $isSliderInfinitive ? 'true' : 'false' ?>,
                    <?php if ($isSliderShowArrows): ?>
                        navigation: {
                            nextEl: '.swiper-button-next<?= $uniqueId ?>',
                            prevEl: '.swiper-button-prev<?= $uniqueId ?>',
                        },
                    <?php endif; ?>
                    autoplay: true,
                    speed: 800,
                    breakpoints: {
                        320: {
                            slidesPerView: <?= $escaper->escapeJs($sliderCountMobile) ?>,
                            spaceBetween: 8,
                        },
                        768: {
                            slidesPerView: <?= $escaper->escapeJs($sliderCountTablet) ?>,
                            spaceBetween: 16,
                        },
                        1024: {
                            slidesPerView: <?= $escaper->escapeJs($sliderCountDesktop) ?>,
                            spaceBetween: 24,
                        },
                    },
                };

                initSwiperSlider(this.$refs.notificationCarouselWrapper, swiperOptions);
            }
        }
    }
</script>

<?php if ($isPreview):  ?>
    <style>
        div[data-content-type="scandiweb_notification_carousel"] {
            background-color: <?= $notificationBgColor ?>;
            width: 100%;
            height: 30px;
        }
    </style>
<?php endif;  ?>

<?= $this->getLayout()
    ->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('Scandiweb_ContentTypes::style/slider-initial-styling.phtml')
    ->setData('slider_count_mobile', $sliderCountMobile)
    ->setData('slider_count_tablet', $sliderCountTablet)
    ->setData('slider_count_desktop', $sliderCountDesktop)
    ->setData('unique_id', $uniqueId)
    ->toHtml(); ?>

<div x-data="initNotificationCarousel<?= $uniqueId ?>" id="<?= $escaper->escapeHtmlAttr($uniqueId) ?>">
    <div class="relative grid">
        <div class="swiper" x-ref="notificationCarouselWrapper">
            <div class="swiper-wrapper flex justify-around text-center">
                <?php foreach ($sections as $index => $section): ?>
                    <div class="swiper-slide">
                        <?= $this->getLayout()
                            ->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Scandiweb_ContentTypes::content-type/notification-carousel/notification-carousel-item.phtml')
                            ->setData('text', $section['text'])
                            ->toHtml(); ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php if ($isSliderShowArrows): ?>
            <button class="swiper-button-prev swiper-button-prev<?= $uniqueId ?> absolute !hidden lg:!flex items-center justify-center !text-white !w-4 !h-4 after:!content-[''] <?= $isPreview ? '!top-[115%]' : '' ?>">
                <?= $heroicons->chevronLeftHtml('rtl:rotate-180', 16, 16, ['aria-hidden' => 'true']); ?>
            </button>
            <button class="swiper-button-next swiper-button-next<?= $uniqueId ?> absolute !hidden lg:!flex items-center justify-center !text-white !w-4 !h-4 after:!content-[''] <?= $isPreview ? '!top-[115%]' : '' ?>">
                <?= $heroicons->chevronRightHtml('rtl:rotate-180', 16, 16, ['aria-hidden' => 'true']); ?>
            </button>
        <?php endif; ?>
    </div>
</div>