<?php
$section = $block->getData('section');
$uspCardColor = $block->getData('usp_card_color');
$ctaType = $block->getData('cta_type');

$title = $section['title'];
$description = $section['description'];
$image = $section['image'];
$ctaText = $section['cta_text'];
$url = $section['url'];
$openInNewTab = $section['open_new_tab']
?>
<div
    class="p-4 lg:p-6 flex flex-col gap-5 rounded-xs"
    <?php if ($uspCardColor): ?>
        style="background-color: <?= $uspCardColor ?>;"
    <?php endif; ?>>
    <div class="flex flex-col gap-4">
        <img
            src="<?= $escaper->escapeHtmlAttr($image) ?>"
            alt="<?= $escaper->escapeHtmlAttr($title)  ?>"
            class="size-12"
            width="48"
            height="48"
            loading="lazy">
        <div class="flex flex-col gap-2 lg:gap-3">
            <h4><?= $escaper->escapeHtml($title) ?></h4>
            <div class="h-full"><?= html_entity_decode($description) ?></div>
        </div>
    </div>
    <?php if ($ctaText): ?>
        <a
            href="<?= $escaper->escapeUrl($url) ?>"
            <?php if ($openInNewTab): ?>
                target="_blank"
            <?php endif; ?>
            class="mt-auto <?= $escaper->escapeHtmlAttr($ctaType) ?>"
            title="<?= $escaper->escapeHtmlAttr($title) ?>">
            <?= $escaper->escapeHtml($ctaText) ?>
        </a>
    <?php endif; ?>
</div>