<?php
$section = $block->getData('section');
$uspCardColor = $block->getData('usp_card_color');
$ctaType = $block->getData('cta_type');

$title = $section['title'];
$description = $section['description'];
$image = $section['image'];
$ctaText = $section['cta_text'];
$url = $section['url'];
$openInNewTab = $section['open_new_tab']
?>
<div
    class="flex flex-row gap-3 rounded-xs p-1"
    <?php if ($uspCardColor): ?>
    style="background-color: <?= $uspCardColor ?>;"
    <?php endif; ?>>
    <img
        src="<?= $escaper->escapeHtmlAttr($image) ?>"
        alt="<?= $escaper->escapeHtmlAttr($title)  ?>"
        class="size-6"
        width="24"
        height="24"
        loading="lazy">
    <div class="flex flex-col">
        <span class="font-bold"><?= $escaper->escapeHtml($title) ?></span>
        <div class="mt-1 text-sm"><?= html_entity_decode($description) ?></div>
        <?php if ($ctaText): ?>
            <a
                href="<?= $escaper->escapeUrl($url) ?>"
                <?php if ($openInNewTab): ?>
                    target="_blank"
                <?php endif; ?>
                class="mt-4 <?= $escaper->escapeHtmlAttr($ctaType) ?>"
                title="<?= $escaper->escapeHtmlAttr($title) ?>">
                <?= $escaper->escapeHtml($ctaText) ?>
            </a>
        <?php endif; ?>
    </div>
</div>