<?php

/**
 * @category  Scandiweb
 * @package   Scandiweb_ContentTypes
 * @copyright Copyright (c) 2025 Scandiweb, Inc (https://scandiweb.com)
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */

$deliveryImage = $block->getImage();
$deliveryText = $block->getDeliveryText();
$ctaText = $block->getCtaText();
$ctaLink = $block->getCtaLink();
?>
<div class="py-3 px-4">
    <div class="flex">
        <?php if ($deliveryImage && isset($deliveryImage['url'])): ?>
            <img class="w-6 h-6 object-contain me-3"
                src="<?= $block->escapeUrl($deliveryImage['url']) ?>"
                alt="<?= $block->escapeHtmlAttr($deliveryText) ?>" >
        <?php endif; ?>
        <div>
            <span>
                <?= $block->escapeHtml($deliveryText) ?>
            </span>
            <?php if ($ctaText && $ctaLink): ?>
                <a href="<?= $block->escapeUrl($ctaLink) ?>"
                    class="ms-0.5">
                    <?= $block->escapeHtml($ctaText) ?>
                </a>
            <?php endif; ?>
        </div>
    </div>
</div>